//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.openapplications.oagis._9.codelists;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentBasisCodeEnumerationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PaymentBasisCodeEnumerationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="InvoiceDate"/>
 *     &lt;enumeration value="ShippingDate"/>
 *     &lt;enumeration value="DeliveryDate"/>
 *     &lt;enumeration value="PurchaseOrderDate"/>
 *     &lt;enumeration value="ReceiptOfGoodsDate"/>
 *     &lt;enumeration value="AcceptanceOfGoodsDate"/>
 *     &lt;enumeration value="AcceptanceOfOrderDate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PaymentBasisCodeEnumerationType", namespace = "http://www.openapplications.org/oagis/9/codelists")
@XmlEnum
public enum PaymentBasisCodeEnumerationType {

    @XmlEnumValue("InvoiceDate")
    INVOICE_DATE("InvoiceDate"),
    @XmlEnumValue("ShippingDate")
    SHIPPING_DATE("ShippingDate"),
    @XmlEnumValue("DeliveryDate")
    DELIVERY_DATE("DeliveryDate"),
    @XmlEnumValue("PurchaseOrderDate")
    PURCHASE_ORDER_DATE("PurchaseOrderDate"),
    @XmlEnumValue("ReceiptOfGoodsDate")
    RECEIPT_OF_GOODS_DATE("ReceiptOfGoodsDate"),
    @XmlEnumValue("AcceptanceOfGoodsDate")
    ACCEPTANCE_OF_GOODS_DATE("AcceptanceOfGoodsDate"),
    @XmlEnumValue("AcceptanceOfOrderDate")
    ACCEPTANCE_OF_ORDER_DATE("AcceptanceOfOrderDate");
    private final String value;

    PaymentBasisCodeEnumerationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PaymentBasisCodeEnumerationType fromValue(String v) {
        for (PaymentBasisCodeEnumerationType c: PaymentBasisCodeEnumerationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
