//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.openapplications.oagis._9;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * CommunicationABIEType is logically derived from UN/CEFACT TBG17 ABIE CommunicationType as defined in the Reusable Aggregate Business Information Entity (RUABIE) XML Schema file.
 * 
 * <p>Java class for CommunicationABIEType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommunicationABIEType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.openapplications.org/oagis/9}ChannelCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.openapplications.org/oagis/9}UseCode" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.openapplications.org/oagis/9}CountryDialing" minOccurs="0"/>
 *             &lt;element ref="{http://www.openapplications.org/oagis/9}AreaDialing" minOccurs="0"/>
 *             &lt;element ref="{http://www.openapplications.org/oagis/9}DialNumber" minOccurs="0"/>
 *             &lt;element ref="{http://www.openapplications.org/oagis/9}Extension" minOccurs="0"/>
 *             &lt;element ref="{http://www.openapplications.org/oagis/9}Access" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://www.openapplications.org/oagis/9}Address" minOccurs="0"/>
 *           &lt;sequence>
 *             &lt;element ref="{http://www.openapplications.org/oagis/9}URI" minOccurs="0"/>
 *             &lt;element ref="{http://www.openapplications.org/oagis/9}HTMLPreferredIndicator" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element ref="{http://www.openapplications.org/oagis/9}Text" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.openapplications.org/oagis/9}Preference" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sequence" type="{http://www.openapplications.org/oagis/9}PositiveIntegerNumericType" />
 *       &lt;attribute name="preferredIndicator" type="{http://www.openapplications.org/oagis/9}IndicatorType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommunicationABIEType", propOrder = {
    "channelCode",
    "useCode",
    "countryDialing",
    "areaDialing",
    "dialNumber",
    "extension",
    "access",
    "address",
    "uri",
    "htmlPreferredIndicator",
    "text",
    "preference"
})
@XmlSeeAlso({
    CommunicationType.class
})
public class CommunicationABIEType {

    @XmlElement(name = "ChannelCode")
    protected CodeType channelCode;
    @XmlElement(name = "UseCode")
    protected CodeType useCode;
    @XmlElement(name = "CountryDialing")
    protected TextType countryDialing;
    @XmlElement(name = "AreaDialing")
    protected TextType areaDialing;
    @XmlElement(name = "DialNumber")
    protected TextType dialNumber;
    @XmlElement(name = "Extension")
    protected TextType extension;
    @XmlElement(name = "Access")
    protected TextType access;
    @XmlElement(name = "Address")
    protected AddressType address;
    @XmlElement(name = "URI")
    protected String uri;
    @XmlElement(name = "HTMLPreferredIndicator")
    protected Boolean htmlPreferredIndicator;
    @XmlElement(name = "Text")
    protected List<TextType> text;
    @XmlElement(name = "Preference")
    protected PreferenceType preference;
    @XmlAttribute(name = "sequence")
    protected BigInteger sequence;
    @XmlAttribute(name = "preferredIndicator")
    protected Boolean preferredIndicator;

    /**
     * Gets the value of the channelCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getChannelCode() {
        return channelCode;
    }

    /**
     * Sets the value of the channelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setChannelCode(CodeType value) {
        this.channelCode = value;
    }

    /**
     * Gets the value of the useCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getUseCode() {
        return useCode;
    }

    /**
     * Sets the value of the useCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setUseCode(CodeType value) {
        this.useCode = value;
    }

    /**
     * Gets the value of the countryDialing property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getCountryDialing() {
        return countryDialing;
    }

    /**
     * Sets the value of the countryDialing property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setCountryDialing(TextType value) {
        this.countryDialing = value;
    }

    /**
     * Gets the value of the areaDialing property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getAreaDialing() {
        return areaDialing;
    }

    /**
     * Sets the value of the areaDialing property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setAreaDialing(TextType value) {
        this.areaDialing = value;
    }

    /**
     * Gets the value of the dialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getDialNumber() {
        return dialNumber;
    }

    /**
     * Sets the value of the dialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setDialNumber(TextType value) {
        this.dialNumber = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setExtension(TextType value) {
        this.extension = value;
    }

    /**
     * Gets the value of the access property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getAccess() {
        return access;
    }

    /**
     * Sets the value of the access property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setAccess(TextType value) {
        this.access = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the uri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getURI() {
        return uri;
    }

    /**
     * Sets the value of the uri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setURI(String value) {
        this.uri = value;
    }

    /**
     * Gets the value of the htmlPreferredIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHTMLPreferredIndicator() {
        return htmlPreferredIndicator;
    }

    /**
     * Sets the value of the htmlPreferredIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHTMLPreferredIndicator(Boolean value) {
        this.htmlPreferredIndicator = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the text property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getText().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getText() {
        if (text == null) {
            text = new ArrayList<TextType>();
        }
        return this.text;
    }

    /**
     * Gets the value of the preference property.
     * 
     * @return
     *     possible object is
     *     {@link PreferenceType }
     *     
     */
    public PreferenceType getPreference() {
        return preference;
    }

    /**
     * Sets the value of the preference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreferenceType }
     *     
     */
    public void setPreference(PreferenceType value) {
        this.preference = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequence(BigInteger value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the preferredIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPreferredIndicator() {
        return preferredIndicator;
    }

    /**
     * Sets the value of the preferredIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPreferredIndicator(Boolean value) {
        this.preferredIndicator = value;
    }

}
