//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AppraisalScheduleEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AppraisalScheduleEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="Annual"/>
 *     &lt;enumeration value="Midyear"/>
 *     &lt;enumeration value="Interim"/>
 *     &lt;enumeration value="Probation"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AppraisalScheduleEnumType")
@XmlEnum
public enum AppraisalScheduleEnumType {

    @XmlEnumValue("Annual")
    ANNUAL("Annual"),
    @XmlEnumValue("Midyear")
    MIDYEAR("Midyear"),
    @XmlEnumValue("Interim")
    INTERIM("Interim"),
    @XmlEnumValue("Probation")
    PROBATION("Probation");
    private final String value;

    AppraisalScheduleEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AppraisalScheduleEnumType fromValue(String v) {
        for (AppraisalScheduleEnumType c: AppraisalScheduleEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
