//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import org.openapplications.oagis._9.CodeType;
import org.openapplications.oagis._9.MeasureType;


/**
 * <p>Java class for AssessmentSubjectType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssessmentSubjectType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.hr-xml.org/3}SubjectID" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}PersonLegalID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}PersonName" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}Communication" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}RaceCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}EthnicityCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}NationalityCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}PrimaryLanguageCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}BirthDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.openapplications.org/oagis/9}AgeMeasure" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}GenderCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}DisabilityIndicator" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}DisabilityTypeCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}AccomodationTypeCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}MilitaryStatusCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}InternalCandidateIndicator" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}UserArea" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssessmentSubjectType", propOrder = {
    "subjectID",
    "personLegalID",
    "personName",
    "communication",
    "raceCode",
    "ethnicityCode",
    "nationalityCode",
    "primaryLanguageCode",
    "birthDate",
    "ageMeasure",
    "genderCode",
    "disabilityIndicator",
    "disabilityTypeCode",
    "accomodationTypeCode",
    "militaryStatusCode",
    "internalCandidateIndicator",
    "userArea"
})
public class AssessmentSubjectType {

    @XmlElement(name = "SubjectID")
    protected IdentifierType subjectID;
    @XmlElement(name = "PersonLegalID")
    protected List<IdentifierType> personLegalID;
    @XmlElement(name = "PersonName")
    protected PersonNameType personName;
    @XmlElement(name = "Communication")
    protected List<CommunicationABIEType> communication;
    @XmlElement(name = "RaceCode")
    protected List<CodeType> raceCode;
    @XmlElement(name = "EthnicityCode")
    protected List<CodeType> ethnicityCode;
    @XmlElement(name = "NationalityCode")
    protected List<CodeType> nationalityCode;
    @XmlElement(name = "PrimaryLanguageCode")
    protected LanguageCodeType primaryLanguageCode;
    @XmlList
    @XmlElement(name = "BirthDate")
    protected List<String> birthDate;
    @XmlElement(name = "AgeMeasure", namespace = "http://www.openapplications.org/oagis/9")
    protected MeasureType ageMeasure;
    @XmlElement(name = "GenderCode")
    protected GenderCodeType genderCode;
    @XmlElement(name = "DisabilityIndicator")
    protected EffectiveDatedIndicatorType disabilityIndicator;
    @XmlElement(name = "DisabilityTypeCode")
    protected List<CodeType> disabilityTypeCode;
    @XmlElement(name = "AccomodationTypeCode")
    protected List<CodeType> accomodationTypeCode;
    @XmlElement(name = "MilitaryStatusCode")
    protected List<StatusCodeType> militaryStatusCode;
    @XmlElement(name = "InternalCandidateIndicator")
    protected Boolean internalCandidateIndicator;
    @XmlElement(name = "UserArea")
    protected UserAreaType userArea;

    /**
     * The test taker or person who takes the assessment or is assessed. 
     * 	
     * OED Assessment n., b. Educ. The process or means of evaluating academic work; an examination or test.
     * 
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getSubjectID() {
        return subjectID;
    }

    /**
     * Sets the value of the subjectID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setSubjectID(IdentifierType value) {
        this.subjectID = value;
    }

    /**
     * A government assigned identifier or
     * 					"official" identifier. In many scenarios,
     * 					an assessment provider would have no need for collecting a PersonLegalID
     * 					(for example, a social insurance number). In some cases, the assessment
     * 					provider may play a role of having first contact with a candidate and may
     * 					have a need to collect such information to support subsequent hiring
     * 					activities or workflow (e.g., employment screening).Gets the value of the personLegalID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personLegalID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonLegalID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getPersonLegalID() {
        if (personLegalID == null) {
            personLegalID = new ArrayList<IdentifierType>();
        }
        return this.personLegalID;
    }

    /**
     * The name of the person subject to the assessment.
     * 
     * @return
     *     possible object is
     *     {@link PersonNameType }
     *     
     */
    public PersonNameType getPersonName() {
        return personName;
    }

    /**
     * Sets the value of the personName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonNameType }
     *     
     */
    public void setPersonName(PersonNameType value) {
        this.personName = value;
    }

    /**
     * A means of contacting the assessment subject. Repeatable for 
     * 					each type of contact method.Gets the value of the communication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the communication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommunication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommunicationABIEType }
     * 
     * 
     */
    public List<CommunicationABIEType> getCommunication() {
        if (communication == null) {
            communication = new ArrayList<CommunicationABIEType>();
        }
        return this.communication;
    }

    /**
     * Gets the value of the raceCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the raceCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRaceCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getRaceCode() {
        if (raceCode == null) {
            raceCode = new ArrayList<CodeType>();
        }
        return this.raceCode;
    }

    /**
     * Gets the value of the ethnicityCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ethnicityCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEthnicityCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getEthnicityCode() {
        if (ethnicityCode == null) {
            ethnicityCode = new ArrayList<CodeType>();
        }
        return this.ethnicityCode;
    }

    /**
     * Gets the value of the nationalityCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nationalityCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNationalityCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getNationalityCode() {
        if (nationalityCode == null) {
            nationalityCode = new ArrayList<CodeType>();
        }
        return this.nationalityCode;
    }

    /**
     * Gets the value of the primaryLanguageCode property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageCodeType }
     *     
     */
    public LanguageCodeType getPrimaryLanguageCode() {
        return primaryLanguageCode;
    }

    /**
     * Sets the value of the primaryLanguageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageCodeType }
     *     
     */
    public void setPrimaryLanguageCode(LanguageCodeType value) {
        this.primaryLanguageCode = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the birthDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBirthDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getBirthDate() {
        if (birthDate == null) {
            birthDate = new ArrayList<String>();
        }
        return this.birthDate;
    }

    /**
     * Gets the value of the ageMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureType }
     *     
     */
    public MeasureType getAgeMeasure() {
        return ageMeasure;
    }

    /**
     * Sets the value of the ageMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureType }
     *     
     */
    public void setAgeMeasure(MeasureType value) {
        this.ageMeasure = value;
    }

    /**
     * Gets the value of the genderCode property.
     * 
     * @return
     *     possible object is
     *     {@link GenderCodeType }
     *     
     */
    public GenderCodeType getGenderCode() {
        return genderCode;
    }

    /**
     * Sets the value of the genderCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenderCodeType }
     *     
     */
    public void setGenderCode(GenderCodeType value) {
        this.genderCode = value;
    }

    /**
     * Gets the value of the disabilityIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link EffectiveDatedIndicatorType }
     *     
     */
    public EffectiveDatedIndicatorType getDisabilityIndicator() {
        return disabilityIndicator;
    }

    /**
     * Sets the value of the disabilityIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link EffectiveDatedIndicatorType }
     *     
     */
    public void setDisabilityIndicator(EffectiveDatedIndicatorType value) {
        this.disabilityIndicator = value;
    }

    /**
     * Gets the value of the disabilityTypeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disabilityTypeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisabilityTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getDisabilityTypeCode() {
        if (disabilityTypeCode == null) {
            disabilityTypeCode = new ArrayList<CodeType>();
        }
        return this.disabilityTypeCode;
    }

    /**
     * Gets the value of the accomodationTypeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accomodationTypeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccomodationTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getAccomodationTypeCode() {
        if (accomodationTypeCode == null) {
            accomodationTypeCode = new ArrayList<CodeType>();
        }
        return this.accomodationTypeCode;
    }

    /**
     * Gets the value of the militaryStatusCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the militaryStatusCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMilitaryStatusCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatusCodeType }
     * 
     * 
     */
    public List<StatusCodeType> getMilitaryStatusCode() {
        if (militaryStatusCode == null) {
            militaryStatusCode = new ArrayList<StatusCodeType>();
        }
        return this.militaryStatusCode;
    }

    /**
     * Gets the value of the internalCandidateIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInternalCandidateIndicator() {
        return internalCandidateIndicator;
    }

    /**
     * Sets the value of the internalCandidateIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInternalCandidateIndicator(Boolean value) {
        this.internalCandidateIndicator = value;
    }

    /**
     * Gets the value of the userArea property.
     * 
     * @return
     *     possible object is
     *     {@link UserAreaType }
     *     
     */
    public UserAreaType getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAreaType }
     *     
     */
    public void setUserArea(UserAreaType value) {
        this.userArea = value;
    }

}
