//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditConsumerReferralType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditConsumerReferralType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.hr-xml.org/3}CreditBureauCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}OrganizationName" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}OrganizationID" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}OrganizationTaxID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}OrganizationLegalID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}InternetDomainName" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}Communication" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}CreditConsumerReferralCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}CreditBusinessClassification" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}AdditionalItem" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditConsumerReferralType", propOrder = {
    "creditBureauCode",
    "organizationName",
    "organizationID",
    "organizationTaxID",
    "organizationLegalID",
    "internetDomainName",
    "communication",
    "creditConsumerReferralCode",
    "creditBusinessClassification",
    "additionalItem"
})
public class CreditConsumerReferralType {

    @XmlElement(name = "CreditBureauCode")
    protected CreditBureauCodeType creditBureauCode;
    @XmlElement(name = "OrganizationName")
    protected OrganizationNameType organizationName;
    @XmlElement(name = "OrganizationID")
    protected IdentifierType organizationID;
    @XmlElement(name = "OrganizationTaxID")
    protected List<IdentifierType> organizationTaxID;
    @XmlElement(name = "OrganizationLegalID")
    protected List<IdentifierType> organizationLegalID;
    @XmlElement(name = "InternetDomainName")
    protected InternetDomainNameType internetDomainName;
    @XmlElement(name = "Communication")
    protected List<CommunicationABIEType> communication;
    @XmlElement(name = "CreditConsumerReferralCode")
    protected List<CreditConsumerReferralCodeType> creditConsumerReferralCode;
    @XmlElement(name = "CreditBusinessClassification")
    protected List<CreditBusinessClassificationType> creditBusinessClassification;
    @XmlElement(name = "AdditionalItem")
    protected List<AdditionalItemType> additionalItem;

    /**
     * Gets the value of the creditBureauCode property.
     * 
     * @return
     *     possible object is
     *     {@link CreditBureauCodeType }
     *     
     */
    public CreditBureauCodeType getCreditBureauCode() {
        return creditBureauCode;
    }

    /**
     * Sets the value of the creditBureauCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditBureauCodeType }
     *     
     */
    public void setCreditBureauCode(CreditBureauCodeType value) {
        this.creditBureauCode = value;
    }

    /**
     * Gets the value of the organizationName property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationNameType }
     *     
     */
    public OrganizationNameType getOrganizationName() {
        return organizationName;
    }

    /**
     * Sets the value of the organizationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationNameType }
     *     
     */
    public void setOrganizationName(OrganizationNameType value) {
        this.organizationName = value;
    }

    /**
     * Gets the value of the organizationID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getOrganizationID() {
        return organizationID;
    }

    /**
     * Sets the value of the organizationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setOrganizationID(IdentifierType value) {
        this.organizationID = value;
    }

    /**
     * Gets the value of the organizationTaxID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizationTaxID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganizationTaxID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getOrganizationTaxID() {
        if (organizationTaxID == null) {
            organizationTaxID = new ArrayList<IdentifierType>();
        }
        return this.organizationTaxID;
    }

    /**
     * Gets the value of the organizationLegalID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organizationLegalID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganizationLegalID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getOrganizationLegalID() {
        if (organizationLegalID == null) {
            organizationLegalID = new ArrayList<IdentifierType>();
        }
        return this.organizationLegalID;
    }

    /**
     * Gets the value of the internetDomainName property.
     * 
     * @return
     *     possible object is
     *     {@link InternetDomainNameType }
     *     
     */
    public InternetDomainNameType getInternetDomainName() {
        return internetDomainName;
    }

    /**
     * Sets the value of the internetDomainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternetDomainNameType }
     *     
     */
    public void setInternetDomainName(InternetDomainNameType value) {
        this.internetDomainName = value;
    }

    /**
     * Gets the value of the communication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the communication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommunication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommunicationABIEType }
     * 
     * 
     */
    public List<CommunicationABIEType> getCommunication() {
        if (communication == null) {
            communication = new ArrayList<CommunicationABIEType>();
        }
        return this.communication;
    }

    /**
     * Gets the value of the creditConsumerReferralCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creditConsumerReferralCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreditConsumerReferralCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreditConsumerReferralCodeType }
     * 
     * 
     */
    public List<CreditConsumerReferralCodeType> getCreditConsumerReferralCode() {
        if (creditConsumerReferralCode == null) {
            creditConsumerReferralCode = new ArrayList<CreditConsumerReferralCodeType>();
        }
        return this.creditConsumerReferralCode;
    }

    /**
     * Gets the value of the creditBusinessClassification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creditBusinessClassification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreditBusinessClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreditBusinessClassificationType }
     * 
     * 
     */
    public List<CreditBusinessClassificationType> getCreditBusinessClassification() {
        if (creditBusinessClassification == null) {
            creditBusinessClassification = new ArrayList<CreditBusinessClassificationType>();
        }
        return this.creditBusinessClassification;
    }

    /**
     * Gets the value of the additionalItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalItemType }
     * 
     * 
     */
    public List<AdditionalItemType> getAdditionalItem() {
        if (additionalItem == null) {
            additionalItem = new ArrayList<AdditionalItemType>();
        }
        return this.additionalItem;
    }

}
