//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditFileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditFileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.hr-xml.org/3}ID" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}CreditBureauCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}FormattedDateTime" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}LastActivityDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}CreditFilePerson" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}CreditEmploymentReport" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}CreditFilePersonAlias" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}AdditionalItem" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.hr-xml.org/3}EffectiveDateAttributeGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditFileType", propOrder = {
    "id",
    "creditBureauCode",
    "formattedDateTime",
    "lastActivityDate",
    "creditFilePerson",
    "creditEmploymentReport",
    "creditFilePersonAlias",
    "additionalItem"
})
public class CreditFileType {

    @XmlElement(name = "ID")
    protected IdentifierType id;
    @XmlElement(name = "CreditBureauCode")
    protected CreditBureauCodeType creditBureauCode;
    @XmlList
    @XmlElement(name = "FormattedDateTime")
    protected List<String> formattedDateTime;
    @XmlList
    @XmlElement(name = "LastActivityDate")
    protected List<String> lastActivityDate;
    @XmlElement(name = "CreditFilePerson")
    protected List<CreditFilePersonType> creditFilePerson;
    @XmlElement(name = "CreditEmploymentReport")
    protected List<CreditEmploymentReportType> creditEmploymentReport;
    @XmlElement(name = "CreditFilePersonAlias")
    protected List<CreditFilePersonType> creditFilePersonAlias;
    @XmlElement(name = "AdditionalItem")
    protected List<AdditionalItemType> additionalItem;
    @XmlAttribute(name = "validFrom")
    protected List<String> validFrom;
    @XmlAttribute(name = "validTo")
    protected List<String> validTo;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the creditBureauCode property.
     * 
     * @return
     *     possible object is
     *     {@link CreditBureauCodeType }
     *     
     */
    public CreditBureauCodeType getCreditBureauCode() {
        return creditBureauCode;
    }

    /**
     * Sets the value of the creditBureauCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreditBureauCodeType }
     *     
     */
    public void setCreditBureauCode(CreditBureauCodeType value) {
        this.creditBureauCode = value;
    }

    /**
     * Gets the value of the formattedDateTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formattedDateTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormattedDateTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFormattedDateTime() {
        if (formattedDateTime == null) {
            formattedDateTime = new ArrayList<String>();
        }
        return this.formattedDateTime;
    }

    /**
     * Gets the value of the lastActivityDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lastActivityDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLastActivityDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLastActivityDate() {
        if (lastActivityDate == null) {
            lastActivityDate = new ArrayList<String>();
        }
        return this.lastActivityDate;
    }

    /**
     * Gets the value of the creditFilePerson property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creditFilePerson property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreditFilePerson().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreditFilePersonType }
     * 
     * 
     */
    public List<CreditFilePersonType> getCreditFilePerson() {
        if (creditFilePerson == null) {
            creditFilePerson = new ArrayList<CreditFilePersonType>();
        }
        return this.creditFilePerson;
    }

    /**
     * Gets the value of the creditEmploymentReport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creditEmploymentReport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreditEmploymentReport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreditEmploymentReportType }
     * 
     * 
     */
    public List<CreditEmploymentReportType> getCreditEmploymentReport() {
        if (creditEmploymentReport == null) {
            creditEmploymentReport = new ArrayList<CreditEmploymentReportType>();
        }
        return this.creditEmploymentReport;
    }

    /**
     * Gets the value of the creditFilePersonAlias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creditFilePersonAlias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreditFilePersonAlias().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreditFilePersonType }
     * 
     * 
     */
    public List<CreditFilePersonType> getCreditFilePersonAlias() {
        if (creditFilePersonAlias == null) {
            creditFilePersonAlias = new ArrayList<CreditFilePersonType>();
        }
        return this.creditFilePersonAlias;
    }

    /**
     * Gets the value of the additionalItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalItemType }
     * 
     * 
     */
    public List<AdditionalItemType> getAdditionalItem() {
        if (additionalItem == null) {
            additionalItem = new ArrayList<AdditionalItemType>();
        }
        return this.additionalItem;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validFrom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidFrom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValidFrom() {
        if (validFrom == null) {
            validFrom = new ArrayList<String>();
        }
        return this.validFrom;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validTo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidTo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValidTo() {
        if (validTo == null) {
            validTo = new ArrayList<String>();
        }
        return this.validTo;
    }

}
