//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditInquiryResultCodeEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CreditInquiryResultCodeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="AccountClosed"/>
 *     &lt;enumeration value="ApplicationPending"/>
 *     &lt;enumeration value="Declined"/>
 *     &lt;enumeration value="DidNotInquire"/>
 *     &lt;enumeration value="NoOpenAccount"/>
 *     &lt;enumeration value="NotALender"/>
 *     &lt;enumeration value="OpenAccountNumberNotIssued"/>
 *     &lt;enumeration value="OpenDiscovered"/>
 *     &lt;enumeration value="OpenPrimaryAccount"/>
 *     &lt;enumeration value="ReportingAgencyInquiry"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CreditInquiryResultCodeEnumType")
@XmlEnum
public enum CreditInquiryResultCodeEnumType {

    @XmlEnumValue("AccountClosed")
    ACCOUNT_CLOSED("AccountClosed"),
    @XmlEnumValue("ApplicationPending")
    APPLICATION_PENDING("ApplicationPending"),
    @XmlEnumValue("Declined")
    DECLINED("Declined"),
    @XmlEnumValue("DidNotInquire")
    DID_NOT_INQUIRE("DidNotInquire"),
    @XmlEnumValue("NoOpenAccount")
    NO_OPEN_ACCOUNT("NoOpenAccount"),
    @XmlEnumValue("NotALender")
    NOT_A_LENDER("NotALender"),
    @XmlEnumValue("OpenAccountNumberNotIssued")
    OPEN_ACCOUNT_NUMBER_NOT_ISSUED("OpenAccountNumberNotIssued"),
    @XmlEnumValue("OpenDiscovered")
    OPEN_DISCOVERED("OpenDiscovered"),
    @XmlEnumValue("OpenPrimaryAccount")
    OPEN_PRIMARY_ACCOUNT("OpenPrimaryAccount"),
    @XmlEnumValue("ReportingAgencyInquiry")
    REPORTING_AGENCY_INQUIRY("ReportingAgencyInquiry"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    CreditInquiryResultCodeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CreditInquiryResultCodeEnumType fromValue(String v) {
        for (CreditInquiryResultCodeEnumType c: CreditInquiryResultCodeEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
