//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.openapplications.oagis._9.CodeType;
import org.openapplications.oagis._9.TextType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:oa="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Qualified_ Development Competency. Details&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:VersionID xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:oa="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;1.0&lt;/ccts:VersionID&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DefinitionText xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:oa="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;A qualified development competency is associated with a learning object or developmental tool. It optionally has a specified required and/or desired level of proficiency and has an explicit or implicit level of importance (weight) among sibling competencies associated with the learning object.&lt;/ccts:DefinitionText&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for DevelopmentCompetencyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DevelopmentCompetencyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.hr-xml.org/3}CompetencyID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}CompetencyName" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}TaxonomyID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}Weight" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}RequiredProficiencyLevel" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}DesiredProficiencyLevel" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}CompetencyClassificationCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}CompetencyDimension" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}CompetencyEvidenceRequirements" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}UserArea" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DevelopmentCompetencyType", propOrder = {
    "competencyID",
    "competencyName",
    "taxonomyID",
    "weight",
    "requiredProficiencyLevel",
    "desiredProficiencyLevel",
    "competencyClassificationCode",
    "competencyDimension",
    "competencyEvidenceRequirements",
    "userArea"
})
public class DevelopmentCompetencyType {

    @XmlElement(name = "CompetencyID")
    protected List<IdentifierType> competencyID;
    @XmlElement(name = "CompetencyName")
    protected TextType competencyName;
    @XmlElement(name = "TaxonomyID")
    protected List<IdentifierType> taxonomyID;
    @XmlElement(name = "Weight")
    protected WeightType weight;
    @XmlElement(name = "RequiredProficiencyLevel")
    protected BaseScoreType requiredProficiencyLevel;
    @XmlElement(name = "DesiredProficiencyLevel")
    protected BaseScoreType desiredProficiencyLevel;
    @XmlElement(name = "CompetencyClassificationCode")
    protected List<CodeType> competencyClassificationCode;
    @XmlElement(name = "CompetencyDimension")
    protected List<CompetencyDimensionType> competencyDimension;
    @XmlElement(name = "CompetencyEvidenceRequirements")
    protected CompetencyEvidenceRequirementsType competencyEvidenceRequirements;
    @XmlElement(name = "UserArea")
    protected UserAreaType userArea;

    /**
     * Gets the value of the competencyID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the competencyID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompetencyID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getCompetencyID() {
        if (competencyID == null) {
            competencyID = new ArrayList<IdentifierType>();
        }
        return this.competencyID;
    }

    /**
     * Gets the value of the competencyName property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getCompetencyName() {
        return competencyName;
    }

    /**
     * Sets the value of the competencyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setCompetencyName(TextType value) {
        this.competencyName = value;
    }

    /**
     * Gets the value of the taxonomyID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taxonomyID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaxonomyID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getTaxonomyID() {
        if (taxonomyID == null) {
            taxonomyID = new ArrayList<IdentifierType>();
        }
        return this.taxonomyID;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link WeightType }
     *     
     */
    public WeightType getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightType }
     *     
     */
    public void setWeight(WeightType value) {
        this.weight = value;
    }

    /**
     * Gets the value of the requiredProficiencyLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BaseScoreType }
     *     
     */
    public BaseScoreType getRequiredProficiencyLevel() {
        return requiredProficiencyLevel;
    }

    /**
     * Sets the value of the requiredProficiencyLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseScoreType }
     *     
     */
    public void setRequiredProficiencyLevel(BaseScoreType value) {
        this.requiredProficiencyLevel = value;
    }

    /**
     * Gets the value of the desiredProficiencyLevel property.
     * 
     * @return
     *     possible object is
     *     {@link BaseScoreType }
     *     
     */
    public BaseScoreType getDesiredProficiencyLevel() {
        return desiredProficiencyLevel;
    }

    /**
     * Sets the value of the desiredProficiencyLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseScoreType }
     *     
     */
    public void setDesiredProficiencyLevel(BaseScoreType value) {
        this.desiredProficiencyLevel = value;
    }

    /**
     * Gets the value of the competencyClassificationCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the competencyClassificationCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompetencyClassificationCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getCompetencyClassificationCode() {
        if (competencyClassificationCode == null) {
            competencyClassificationCode = new ArrayList<CodeType>();
        }
        return this.competencyClassificationCode;
    }

    /**
     * Gets the value of the competencyDimension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the competencyDimension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompetencyDimension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompetencyDimensionType }
     * 
     * 
     */
    public List<CompetencyDimensionType> getCompetencyDimension() {
        if (competencyDimension == null) {
            competencyDimension = new ArrayList<CompetencyDimensionType>();
        }
        return this.competencyDimension;
    }

    /**
     * Gets the value of the competencyEvidenceRequirements property.
     * 
     * @return
     *     possible object is
     *     {@link CompetencyEvidenceRequirementsType }
     *     
     */
    public CompetencyEvidenceRequirementsType getCompetencyEvidenceRequirements() {
        return competencyEvidenceRequirements;
    }

    /**
     * Sets the value of the competencyEvidenceRequirements property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompetencyEvidenceRequirementsType }
     *     
     */
    public void setCompetencyEvidenceRequirements(CompetencyEvidenceRequirementsType value) {
        this.competencyEvidenceRequirements = value;
    }

    /**
     * Gets the value of the userArea property.
     * 
     * @return
     *     possible object is
     *     {@link UserAreaType }
     *     
     */
    public UserAreaType getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAreaType }
     *     
     */
    public void setUserArea(UserAreaType value) {
        this.userArea = value;
    }

}
