//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EPMAppraisalScheduleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EPMAppraisalScheduleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.hr-xml.org/3}FormattedDateTime" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}AppraisalPeriod" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}AppraisalScheduleCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}AppraisalReasonCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}Preparer" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}UserArea" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EPMAppraisalScheduleType", propOrder = {
    "formattedDateTime",
    "appraisalPeriod",
    "appraisalScheduleCode",
    "appraisalReasonCode",
    "preparer",
    "userArea"
})
public class EPMAppraisalScheduleType {

    @XmlList
    @XmlElement(name = "FormattedDateTime")
    protected List<String> formattedDateTime;
    @XmlElement(name = "AppraisalPeriod")
    protected FreeFormEffectivePeriodType appraisalPeriod;
    @XmlElement(name = "AppraisalScheduleCode")
    protected AppraisalScheduleCodeType appraisalScheduleCode;
    @XmlElement(name = "AppraisalReasonCode")
    protected AppraisalReasonCodeType appraisalReasonCode;
    @XmlElement(name = "Preparer")
    protected SpecifiedPersonType preparer;
    @XmlElement(name = "UserArea")
    protected UserAreaType userArea;

    /**
     * Gets the value of the formattedDateTime property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formattedDateTime property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormattedDateTime().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFormattedDateTime() {
        if (formattedDateTime == null) {
            formattedDateTime = new ArrayList<String>();
        }
        return this.formattedDateTime;
    }

    /**
     * Gets the value of the appraisalPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link FreeFormEffectivePeriodType }
     *     
     */
    public FreeFormEffectivePeriodType getAppraisalPeriod() {
        return appraisalPeriod;
    }

    /**
     * Sets the value of the appraisalPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeFormEffectivePeriodType }
     *     
     */
    public void setAppraisalPeriod(FreeFormEffectivePeriodType value) {
        this.appraisalPeriod = value;
    }

    /**
     * Gets the value of the appraisalScheduleCode property.
     * 
     * @return
     *     possible object is
     *     {@link AppraisalScheduleCodeType }
     *     
     */
    public AppraisalScheduleCodeType getAppraisalScheduleCode() {
        return appraisalScheduleCode;
    }

    /**
     * Sets the value of the appraisalScheduleCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppraisalScheduleCodeType }
     *     
     */
    public void setAppraisalScheduleCode(AppraisalScheduleCodeType value) {
        this.appraisalScheduleCode = value;
    }

    /**
     * Gets the value of the appraisalReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link AppraisalReasonCodeType }
     *     
     */
    public AppraisalReasonCodeType getAppraisalReasonCode() {
        return appraisalReasonCode;
    }

    /**
     * Sets the value of the appraisalReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppraisalReasonCodeType }
     *     
     */
    public void setAppraisalReasonCode(AppraisalReasonCodeType value) {
        this.appraisalReasonCode = value;
    }

    /**
     * Gets the value of the preparer property.
     * 
     * @return
     *     possible object is
     *     {@link SpecifiedPersonType }
     *     
     */
    public SpecifiedPersonType getPreparer() {
        return preparer;
    }

    /**
     * Sets the value of the preparer property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecifiedPersonType }
     *     
     */
    public void setPreparer(SpecifiedPersonType value) {
        this.preparer = value;
    }

    /**
     * Gets the value of the userArea property.
     * 
     * @return
     *     possible object is
     *     {@link UserAreaType }
     *     
     */
    public UserAreaType getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAreaType }
     *     
     */
    public void setUserArea(UserAreaType value) {
        this.userArea = value;
    }

}
