//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:oa="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Employee Performance Management_ Participant Dossier. Details&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DefinitionText xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:oa="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Contains a collection of data about a performance management (EPM) process participant. This usually would be an employee, but could be an external participant, such as a rater within an appraisal process. OED dossier n: "A bundle of papers or documents referring to some matter; esp. a bundle of papers or information about a person."&lt;/ccts:DefinitionText&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for EPMParticipantDossierType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EPMParticipantDossierType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.hr-xml.org/3}EPMPerson" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}EPMEmployee" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}EPMEmployment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}EPMDeployment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}EPMRemuneration" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}EPMAppraisalSchedule" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}EPMResultSummary" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}RaterParticipation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}UserArea" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.hr-xml.org/3}EffectiveDateAttributeGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EPMParticipantDossierType", propOrder = {
    "epmPerson",
    "epmEmployee",
    "epmEmployment",
    "epmDeployment",
    "epmRemuneration",
    "epmAppraisalSchedule",
    "epmResultSummary",
    "raterParticipation",
    "userArea"
})
public class EPMParticipantDossierType {

    @XmlElement(name = "EPMPerson")
    protected EPMPersonType epmPerson;
    @XmlElement(name = "EPMEmployee")
    protected List<EPMEmployeeType> epmEmployee;
    @XmlElement(name = "EPMEmployment")
    protected List<EmploymentBaseType> epmEmployment;
    @XmlElement(name = "EPMDeployment")
    protected List<EPMDeploymentType> epmDeployment;
    @XmlElement(name = "EPMRemuneration")
    protected List<EPMRemunerationType> epmRemuneration;
    @XmlElement(name = "EPMAppraisalSchedule")
    protected List<EPMAppraisalScheduleType> epmAppraisalSchedule;
    @XmlElement(name = "EPMResultSummary")
    protected List<EPMResultSummaryType> epmResultSummary;
    @XmlElement(name = "RaterParticipation")
    protected List<RaterParticipationType> raterParticipation;
    @XmlElement(name = "UserArea")
    protected UserAreaType userArea;
    @XmlAttribute(name = "validFrom")
    protected List<String> validFrom;
    @XmlAttribute(name = "validTo")
    protected List<String> validTo;

    /**
     * Gets the value of the epmPerson property.
     * 
     * @return
     *     possible object is
     *     {@link EPMPersonType }
     *     
     */
    public EPMPersonType getEPMPerson() {
        return epmPerson;
    }

    /**
     * Sets the value of the epmPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link EPMPersonType }
     *     
     */
    public void setEPMPerson(EPMPersonType value) {
        this.epmPerson = value;
    }

    /**
     * Gets the value of the epmEmployee property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epmEmployee property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEPMEmployee().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EPMEmployeeType }
     * 
     * 
     */
    public List<EPMEmployeeType> getEPMEmployee() {
        if (epmEmployee == null) {
            epmEmployee = new ArrayList<EPMEmployeeType>();
        }
        return this.epmEmployee;
    }

    /**
     * Gets the value of the epmEmployment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epmEmployment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEPMEmployment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmploymentBaseType }
     * 
     * 
     */
    public List<EmploymentBaseType> getEPMEmployment() {
        if (epmEmployment == null) {
            epmEmployment = new ArrayList<EmploymentBaseType>();
        }
        return this.epmEmployment;
    }

    /**
     * Gets the value of the epmDeployment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epmDeployment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEPMDeployment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EPMDeploymentType }
     * 
     * 
     */
    public List<EPMDeploymentType> getEPMDeployment() {
        if (epmDeployment == null) {
            epmDeployment = new ArrayList<EPMDeploymentType>();
        }
        return this.epmDeployment;
    }

    /**
     * Gets the value of the epmRemuneration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epmRemuneration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEPMRemuneration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EPMRemunerationType }
     * 
     * 
     */
    public List<EPMRemunerationType> getEPMRemuneration() {
        if (epmRemuneration == null) {
            epmRemuneration = new ArrayList<EPMRemunerationType>();
        }
        return this.epmRemuneration;
    }

    /**
     * Contains information about the next scheduled performance appraisal or parameters related to the scheduling of future performance appraisals.Gets the value of the epmAppraisalSchedule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epmAppraisalSchedule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEPMAppraisalSchedule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EPMAppraisalScheduleType }
     * 
     * 
     */
    public List<EPMAppraisalScheduleType> getEPMAppraisalSchedule() {
        if (epmAppraisalSchedule == null) {
            epmAppraisalSchedule = new ArrayList<EPMAppraisalScheduleType>();
        }
        return this.epmAppraisalSchedule;
    }

    /**
     * Contains information about a completed performance evaluation or appraisal.Gets the value of the epmResultSummary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the epmResultSummary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEPMResultSummary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EPMResultSummaryType }
     * 
     * 
     */
    public List<EPMResultSummaryType> getEPMResultSummary() {
        if (epmResultSummary == null) {
            epmResultSummary = new ArrayList<EPMResultSummaryType>();
        }
        return this.epmResultSummary;
    }

    /**
     * Contains information related to participation as a rater within an employee performance management process.Gets the value of the raterParticipation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the raterParticipation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRaterParticipation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RaterParticipationType }
     * 
     * 
     */
    public List<RaterParticipationType> getRaterParticipation() {
        if (raterParticipation == null) {
            raterParticipation = new ArrayList<RaterParticipationType>();
        }
        return this.raterParticipation;
    }

    /**
     * Gets the value of the userArea property.
     * 
     * @return
     *     possible object is
     *     {@link UserAreaType }
     *     
     */
    public UserAreaType getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAreaType }
     *     
     */
    public void setUserArea(UserAreaType value) {
        this.userArea = value;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validFrom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidFrom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValidFrom() {
        if (validFrom == null) {
            validFrom = new ArrayList<String>();
        }
        return this.validFrom;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validTo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidTo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValidTo() {
        if (validTo == null) {
            validTo = new ArrayList<String>();
        }
        return this.validTo;
    }

}
