//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HealthcareProviderRelationshipCodeEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HealthcareProviderRelationshipCodeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="EstablishedPatient"/>
 *     &lt;enumeration value="NotEstablishedPatient"/>
 *     &lt;enumeration value="NotKnown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HealthcareProviderRelationshipCodeEnumType")
@XmlEnum
public enum HealthcareProviderRelationshipCodeEnumType {

    @XmlEnumValue("EstablishedPatient")
    ESTABLISHED_PATIENT("EstablishedPatient"),
    @XmlEnumValue("NotEstablishedPatient")
    NOT_ESTABLISHED_PATIENT("NotEstablishedPatient"),
    @XmlEnumValue("NotKnown")
    NOT_KNOWN("NotKnown");
    private final String value;

    HealthcareProviderRelationshipCodeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HealthcareProviderRelationshipCodeEnumType fromValue(String v) {
        for (HealthcareProviderRelationshipCodeEnumType c: HealthcareProviderRelationshipCodeEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
