//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.openapplications.oagis._9.TextType;


/**
 * <p>Java class for InPersonApplicationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InPersonApplicationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.hr-xml.org/3}Address" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}TravelDirections" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}MapLink" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}AdditionalInstructions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InPersonApplicationType", propOrder = {
    "address",
    "travelDirections",
    "mapLink",
    "additionalInstructions"
})
public class InPersonApplicationType {

    @XmlElement(name = "Address")
    protected AddressType address;
    @XmlElement(name = "TravelDirections")
    protected TextType travelDirections;
    @XmlElement(name = "MapLink")
    protected String mapLink;
    @XmlElement(name = "AdditionalInstructions")
    protected String additionalInstructions;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAddress(AddressType value) {
        this.address = value;
    }

    /**
     * Gets the value of the travelDirections property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getTravelDirections() {
        return travelDirections;
    }

    /**
     * Sets the value of the travelDirections property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setTravelDirections(TextType value) {
        this.travelDirections = value;
    }

    /**
     * Gets the value of the mapLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMapLink() {
        return mapLink;
    }

    /**
     * Sets the value of the mapLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMapLink(String value) {
        this.mapLink = value;
    }

    /**
     * Gets the value of the additionalInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInstructions() {
        return additionalInstructions;
    }

    /**
     * Sets the value of the additionalInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInstructions(String value) {
        this.additionalInstructions = value;
    }

}
