//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for JPNoLimitStaffingTypeCodeEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="JPNoLimitStaffingTypeCodeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="JobCategoryByOrdinance"/>
 *     &lt;enumeration value="ProjectWithPeriod"/>
 *     &lt;enumeration value="WorkWithPeriod"/>
 *     &lt;enumeration value="MaternityLeave"/>
 *     &lt;enumeration value="CaringLeave"/>
 *     &lt;enumeration value="SpecialCases"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "JPNoLimitStaffingTypeCodeEnumType")
@XmlEnum
public enum JPNoLimitStaffingTypeCodeEnumType {

    @XmlEnumValue("JobCategoryByOrdinance")
    JOB_CATEGORY_BY_ORDINANCE("JobCategoryByOrdinance"),
    @XmlEnumValue("ProjectWithPeriod")
    PROJECT_WITH_PERIOD("ProjectWithPeriod"),
    @XmlEnumValue("WorkWithPeriod")
    WORK_WITH_PERIOD("WorkWithPeriod"),
    @XmlEnumValue("MaternityLeave")
    MATERNITY_LEAVE("MaternityLeave"),
    @XmlEnumValue("CaringLeave")
    CARING_LEAVE("CaringLeave"),
    @XmlEnumValue("SpecialCases")
    SPECIAL_CASES("SpecialCases");
    private final String value;

    JPNoLimitStaffingTypeCodeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static JPNoLimitStaffingTypeCodeEnumType fromValue(String v) {
        for (JPNoLimitStaffingTypeCodeEnumType c: JPNoLimitStaffingTypeCodeEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
