//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:CategoryCode xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:oa="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;ABIE&lt;/ccts:CategoryCode&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DictionaryEntryName xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:oa="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Leave. Details&lt;/ccts:DictionaryEntryName&gt;
 * </pre>
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;ccts:DefinitionText xmlns:ccts="urn:un:unece:uncefact:documentation:1.1" xmlns="http://www.hr-xml.org/3" xmlns:oa="http://www.openapplications.org/oagis/9" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;Contains dates and other metadata describing and classifying a period of leave.  OED leave, n. 	"(a) leave of absence, or simply leave, permission to be absent from a post of duty. (See also sick-leave.) on leave: absent from duty by permission.  (b) Hence, the period of such absence."
 * &lt;/ccts:DefinitionText&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for LeaveType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LeaveType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.hr-xml.org/3}LeaveStatusCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}LeaveRemunerationCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}LeaveReasonCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}LeaveStartDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}LastWorkedDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}LastPaidDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}ScheduledWorkReturnDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}WorkReturnDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LeaveType", propOrder = {
    "leaveStatusCode",
    "leaveRemunerationCode",
    "leaveReasonCode",
    "leaveStartDate",
    "lastWorkedDate",
    "lastPaidDate",
    "scheduledWorkReturnDate",
    "workReturnDate"
})
public class LeaveType {

    @XmlElement(name = "LeaveStatusCode")
    protected LeaveStatusCodeType leaveStatusCode;
    @XmlElement(name = "LeaveRemunerationCode")
    protected RemunerationStatusCodeEnumType leaveRemunerationCode;
    @XmlElement(name = "LeaveReasonCode")
    protected StatusCodeType leaveReasonCode;
    @XmlList
    @XmlElement(name = "LeaveStartDate")
    protected List<String> leaveStartDate;
    @XmlList
    @XmlElement(name = "LastWorkedDate")
    protected List<String> lastWorkedDate;
    @XmlList
    @XmlElement(name = "LastPaidDate")
    protected List<String> lastPaidDate;
    @XmlList
    @XmlElement(name = "ScheduledWorkReturnDate")
    protected List<String> scheduledWorkReturnDate;
    @XmlList
    @XmlElement(name = "WorkReturnDate")
    protected List<String> workReturnDate;

    /**
     * Indicates whether the reported or instance of leave is currently active or a inactive.
     * 
     * @return
     *     possible object is
     *     {@link LeaveStatusCodeType }
     *     
     */
    public LeaveStatusCodeType getLeaveStatusCode() {
        return leaveStatusCode;
    }

    /**
     * Sets the value of the leaveStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link LeaveStatusCodeType }
     *     
     */
    public void setLeaveStatusCode(LeaveStatusCodeType value) {
        this.leaveStatusCode = value;
    }

    /**
     * Gets the value of the leaveRemunerationCode property.
     * 
     * @return
     *     possible object is
     *     {@link RemunerationStatusCodeEnumType }
     *     
     */
    public RemunerationStatusCodeEnumType getLeaveRemunerationCode() {
        return leaveRemunerationCode;
    }

    /**
     * Sets the value of the leaveRemunerationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RemunerationStatusCodeEnumType }
     *     
     */
    public void setLeaveRemunerationCode(RemunerationStatusCodeEnumType value) {
        this.leaveRemunerationCode = value;
    }

    /**
     * A code classifying the reason for the leave. This 
     * 			element extends CodeType with an "effectiveDate" (type xsd:date). This 
     * 			allows tracking of the date the leave reason was effective. This may have 
     * 			utility in recordkeeping connected with medical and family leave mandates.
     * 
     * @return
     *     possible object is
     *     {@link StatusCodeType }
     *     
     */
    public StatusCodeType getLeaveReasonCode() {
        return leaveReasonCode;
    }

    /**
     * Sets the value of the leaveReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCodeType }
     *     
     */
    public void setLeaveReasonCode(StatusCodeType value) {
        this.leaveReasonCode = value;
    }

    /**
     * Gets the value of the leaveStartDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the leaveStartDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLeaveStartDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLeaveStartDate() {
        if (leaveStartDate == null) {
            leaveStartDate = new ArrayList<String>();
        }
        return this.leaveStartDate;
    }

    /**
     * Gets the value of the lastWorkedDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lastWorkedDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLastWorkedDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLastWorkedDate() {
        if (lastWorkedDate == null) {
            lastWorkedDate = new ArrayList<String>();
        }
        return this.lastWorkedDate;
    }

    /**
     * Gets the value of the lastPaidDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lastPaidDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLastPaidDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLastPaidDate() {
        if (lastPaidDate == null) {
            lastPaidDate = new ArrayList<String>();
        }
        return this.lastPaidDate;
    }

    /**
     * Gets the value of the scheduledWorkReturnDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scheduledWorkReturnDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScheduledWorkReturnDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getScheduledWorkReturnDate() {
        if (scheduledWorkReturnDate == null) {
            scheduledWorkReturnDate = new ArrayList<String>();
        }
        return this.scheduledWorkReturnDate;
    }

    /**
     * Gets the value of the workReturnDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workReturnDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorkReturnDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getWorkReturnDate() {
        if (workReturnDate == null) {
            workReturnDate = new ArrayList<String>();
        }
        return this.workReturnDate;
    }

}
