//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.openapplications.oagis._9.CodeType;


/**
 * Contains basic information about a position located within (a "member" of) a particular organization unit.
 * 
 * <p>Java class for MemberPositionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MemberPositionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.hr-xml.org/3}PositionID" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}PositionTitle" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}PositionTypeCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}UnitSupervisorIndicator" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}ReportsToPosition" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}ReportsToPerson" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}RelatedPostion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}PositionIncumbent" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}AdditionalItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}UserArea" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.hr-xml.org/3}EffectiveDateAttributeGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MemberPositionType", propOrder = {
    "positionID",
    "positionTitle",
    "positionTypeCode",
    "unitSupervisorIndicator",
    "reportsToPosition",
    "reportsToPerson",
    "relatedPostion",
    "positionIncumbent",
    "additionalItem",
    "userArea"
})
public class MemberPositionType {

    @XmlElement(name = "PositionID")
    protected IdentifierType positionID;
    @XmlElement(name = "PositionTitle")
    protected PositionTitleType positionTitle;
    @XmlElement(name = "PositionTypeCode")
    protected List<CodeType> positionTypeCode;
    @XmlElement(name = "UnitSupervisorIndicator")
    protected Boolean unitSupervisorIndicator;
    @XmlElement(name = "ReportsToPosition")
    protected List<ReportsToPositionType> reportsToPosition;
    @XmlElement(name = "ReportsToPerson")
    protected List<ReportsToPersonType> reportsToPerson;
    @XmlElement(name = "RelatedPostion")
    protected List<RelatedPostionType> relatedPostion;
    @XmlElement(name = "PositionIncumbent")
    protected PositionIncumbentType positionIncumbent;
    @XmlElement(name = "AdditionalItem")
    protected List<AdditionalItemType> additionalItem;
    @XmlElement(name = "UserArea")
    protected UserAreaType userArea;
    @XmlAttribute(name = "validFrom")
    protected List<String> validFrom;
    @XmlAttribute(name = "validTo")
    protected List<String> validTo;

    /**
     * Gets the value of the positionID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getPositionID() {
        return positionID;
    }

    /**
     * Sets the value of the positionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setPositionID(IdentifierType value) {
        this.positionID = value;
    }

    /**
     * Gets the value of the positionTitle property.
     * 
     * @return
     *     possible object is
     *     {@link PositionTitleType }
     *     
     */
    public PositionTitleType getPositionTitle() {
        return positionTitle;
    }

    /**
     * Sets the value of the positionTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionTitleType }
     *     
     */
    public void setPositionTitle(PositionTitleType value) {
        this.positionTitle = value;
    }

    /**
     * Gets the value of the positionTypeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the positionTypeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPositionTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getPositionTypeCode() {
        if (positionTypeCode == null) {
            positionTypeCode = new ArrayList<CodeType>();
        }
        return this.positionTypeCode;
    }

    /**
     * Gets the value of the unitSupervisorIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isUnitSupervisorIndicator() {
        return unitSupervisorIndicator;
    }

    /**
     * Sets the value of the unitSupervisorIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUnitSupervisorIndicator(Boolean value) {
        this.unitSupervisorIndicator = value;
    }

    /**
     * Gets the value of the reportsToPosition property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportsToPosition property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportsToPosition().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportsToPositionType }
     * 
     * 
     */
    public List<ReportsToPositionType> getReportsToPosition() {
        if (reportsToPosition == null) {
            reportsToPosition = new ArrayList<ReportsToPositionType>();
        }
        return this.reportsToPosition;
    }

    /**
     * Gets the value of the reportsToPerson property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportsToPerson property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportsToPerson().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportsToPersonType }
     * 
     * 
     */
    public List<ReportsToPersonType> getReportsToPerson() {
        if (reportsToPerson == null) {
            reportsToPerson = new ArrayList<ReportsToPersonType>();
        }
        return this.reportsToPerson;
    }

    /**
     * Gets the value of the relatedPostion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedPostion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedPostion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedPostionType }
     * 
     * 
     */
    public List<RelatedPostionType> getRelatedPostion() {
        if (relatedPostion == null) {
            relatedPostion = new ArrayList<RelatedPostionType>();
        }
        return this.relatedPostion;
    }

    /**
     * Gets the value of the positionIncumbent property.
     * 
     * @return
     *     possible object is
     *     {@link PositionIncumbentType }
     *     
     */
    public PositionIncumbentType getPositionIncumbent() {
        return positionIncumbent;
    }

    /**
     * Sets the value of the positionIncumbent property.
     * 
     * @param value
     *     allowed object is
     *     {@link PositionIncumbentType }
     *     
     */
    public void setPositionIncumbent(PositionIncumbentType value) {
        this.positionIncumbent = value;
    }

    /**
     * Gets the value of the additionalItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalItemType }
     * 
     * 
     */
    public List<AdditionalItemType> getAdditionalItem() {
        if (additionalItem == null) {
            additionalItem = new ArrayList<AdditionalItemType>();
        }
        return this.additionalItem;
    }

    /**
     * Gets the value of the userArea property.
     * 
     * @return
     *     possible object is
     *     {@link UserAreaType }
     *     
     */
    public UserAreaType getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAreaType }
     *     
     */
    public void setUserArea(UserAreaType value) {
        this.userArea = value;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validFrom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidFrom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValidFrom() {
        if (validFrom == null) {
            validFrom = new ArrayList<String>();
        }
        return this.validFrom;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validTo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidTo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValidTo() {
        if (validTo == null) {
            validTo = new ArrayList<String>();
        }
        return this.validTo;
    }

}
