//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.openapplications.oagis._9.CodeType;
import org.openapplications.oagis._9.TextType;


/**
 * <p>Java class for RelatedCompetencyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RelatedCompetencyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.hr-xml.org/3}CompetencyID" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}CompetencyName" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}CompetencyRelationshipCode" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelatedCompetencyType", propOrder = {
    "competencyID",
    "competencyName",
    "competencyRelationshipCode"
})
public class RelatedCompetencyType {

    @XmlElement(name = "CompetencyID")
    protected IdentifierType competencyID;
    @XmlElement(name = "CompetencyName")
    protected TextType competencyName;
    @XmlElement(name = "CompetencyRelationshipCode")
    protected List<CodeType> competencyRelationshipCode;

    /**
     * Gets the value of the competencyID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getCompetencyID() {
        return competencyID;
    }

    /**
     * Sets the value of the competencyID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setCompetencyID(IdentifierType value) {
        this.competencyID = value;
    }

    /**
     * Gets the value of the competencyName property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getCompetencyName() {
        return competencyName;
    }

    /**
     * Sets the value of the competencyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setCompetencyName(TextType value) {
        this.competencyName = value;
    }

    /**
     * Gets the value of the competencyRelationshipCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the competencyRelationshipCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompetencyRelationshipCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeType }
     * 
     * 
     */
    public List<CodeType> getCompetencyRelationshipCode() {
        if (competencyRelationshipCode == null) {
            competencyRelationshipCode = new ArrayList<CodeType>();
        }
        return this.competencyRelationshipCode;
    }

}
