//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScreeningResultTypeEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ScreeningResultTypeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="Result"/>
 *     &lt;enumeration value="SummaryResult"/>
 *     &lt;enumeration value="Error"/>
 *     &lt;enumeration value="Message"/>
 *     &lt;enumeration value="Status"/>
 *     &lt;enumeration value="ManagementReport"/>
 *     &lt;enumeration value="MultipleResults"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ScreeningResultTypeEnumType")
@XmlEnum
public enum ScreeningResultTypeEnumType {


    /**
     * Indicates the a result for a screening package or specific screening is provided.
     * 
     */
    @XmlEnumValue("Result")
    RESULT("Result"),

    /**
     * Indicates that a summary result is provided. This generally would consist 
     * 			of one or more of the following: 1. a ScreeningResultCode; 2. a Description; and 3. an "access point" where full or complete information can be 
     * 			reviewed.
     * 
     */
    @XmlEnumValue("SummaryResult")
    SUMMARY_RESULT("SummaryResult"),
    @XmlEnumValue("Error")
    ERROR("Error"),

    /**
     * This would usually be used to communicate an instruction. For example, that a release
     * 			or consent is required to fulfill the order.
     * 
     */
    @XmlEnumValue("Message")
    MESSAGE("Message"),

    /**
     * Used to convey an interim status about an order that is in progress.
     * 
     */
    @XmlEnumValue("Status")
    STATUS("Status"),

    /**
     * Indicates that the information provided is in response to a report
     * 			request.
     * 
     */
    @XmlEnumValue("ManagementReport")
    MANAGEMENT_REPORT("ManagementReport"),

    /**
     * Indicates that multiple results are provided.
     * 
     */
    @XmlEnumValue("MultipleResults")
    MULTIPLE_RESULTS("MultipleResults");
    private final String value;

    ScreeningResultTypeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ScreeningResultTypeEnumType fromValue(String v) {
        for (ScreeningResultTypeEnumType c: ScreeningResultTypeEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
