//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.openapplications.oagis._9.CodeType;
import org.openapplications.oagis._9.NoteType;


/**
 * <p>Java class for ScreeningType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScreeningType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.hr-xml.org/3}ScreeningID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}PartyReportingIDs" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}InitialStatusCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}ScreeningSubjectID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}ScreeningSearchTypeCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}ScreeningSearchTypeQualifierCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}ScreeningUser" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}ServiceLevelCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}QuestionSetID" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}SearchAbuse" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}SearchAlcohol" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}SearchCredit" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}SearchCriminal" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}SearchDrug" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}SearchEducation" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}SearchEmployment" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}SearchLicense" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}SearchMilitary" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}SearchOther" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}SearchReference" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}SearchSanction" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}Attachment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}Comment" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}AdditionalItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}UserArea" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScreeningType", propOrder = {
    "screeningID",
    "partyReportingIDs",
    "initialStatusCode",
    "screeningSubjectID",
    "screeningSearchTypeCode",
    "screeningSearchTypeQualifierCode",
    "screeningUser",
    "serviceLevelCode",
    "questionSetID",
    "searchAbuse",
    "searchAlcohol",
    "searchCredit",
    "searchCriminal",
    "searchDrug",
    "searchEducation",
    "searchEmployment",
    "searchLicense",
    "searchMilitary",
    "searchOther",
    "searchReference",
    "searchSanction",
    "attachment",
    "comment",
    "additionalItem",
    "userArea"
})
public class ScreeningType {

    @XmlElement(name = "ScreeningID")
    protected List<ScreeningIdentifierType> screeningID;
    @XmlElement(name = "PartyReportingIDs")
    protected List<IDSetType> partyReportingIDs;
    @XmlElement(name = "InitialStatusCode")
    protected InitialStatusCodeType initialStatusCode;
    @XmlElement(name = "ScreeningSubjectID")
    protected List<ScreeningIdentifierType> screeningSubjectID;
    @XmlElement(name = "ScreeningSearchTypeCode")
    protected ScreeningSearchTypeCode screeningSearchTypeCode;
    @XmlElement(name = "ScreeningSearchTypeQualifierCode")
    protected ScreeningSearchTypeQualifierCodeType screeningSearchTypeQualifierCode;
    @XmlElement(name = "ScreeningUser")
    protected List<ScreeningUserType> screeningUser;
    @XmlElement(name = "ServiceLevelCode")
    protected CodeType serviceLevelCode;
    @XmlElement(name = "QuestionSetID")
    protected IdentifierType questionSetID;
    @XmlElement(name = "SearchAbuse")
    protected SearchAbuseType searchAbuse;
    @XmlElement(name = "SearchAlcohol")
    protected SearchAlcoholType searchAlcohol;
    @XmlElement(name = "SearchCredit")
    protected SearchCreditType searchCredit;
    @XmlElement(name = "SearchCriminal")
    protected SearchCriminalType searchCriminal;
    @XmlElement(name = "SearchDrug")
    protected SearchDrugType searchDrug;
    @XmlElement(name = "SearchEducation")
    protected SearchEducationType searchEducation;
    @XmlElement(name = "SearchEmployment")
    protected SearchEmploymentType searchEmployment;
    @XmlElement(name = "SearchLicense")
    protected SearchLicenseType searchLicense;
    @XmlElement(name = "SearchMilitary")
    protected SearchMilitaryType searchMilitary;
    @XmlElement(name = "SearchOther")
    protected SearchOtherType searchOther;
    @XmlElement(name = "SearchReference")
    protected SearchReferenceType searchReference;
    @XmlElement(name = "SearchSanction")
    protected SearchSanctionType searchSanction;
    @XmlElement(name = "Attachment")
    protected List<AttachmentType> attachment;
    @XmlElement(name = "Comment")
    protected List<NoteType> comment;
    @XmlElement(name = "AdditionalItem")
    protected List<AdditionalItemType> additionalItem;
    @XmlElement(name = "UserArea")
    protected UserAreaType userArea;

    /**
     * 
     * Example Usage:
     * Screening/ID 
     *               agencyRole = Requester
     *               schemeAgencyID = PeopleClick
     *  Screening/ID  
     *               agencyRole = Supplier
     *               schemeAgencyID = FirstAdvantage
     * Screening/ID  
     *               agencyRole = Customer
     *               schemeAgencyID = Acme Corp
     * Gets the value of the screeningID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the screeningID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScreeningID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScreeningIdentifierType }
     * 
     * 
     */
    public List<ScreeningIdentifierType> getScreeningID() {
        if (screeningID == null) {
            screeningID = new ArrayList<ScreeningIdentifierType>();
        }
        return this.screeningID;
    }

    /**
     * Gets the value of the partyReportingIDs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyReportingIDs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyReportingIDs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IDSetType }
     * 
     * 
     */
    public List<IDSetType> getPartyReportingIDs() {
        if (partyReportingIDs == null) {
            partyReportingIDs = new ArrayList<IDSetType>();
        }
        return this.partyReportingIDs;
    }

    /**
     * Gets the value of the initialStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link InitialStatusCodeType }
     *     
     */
    public InitialStatusCodeType getInitialStatusCode() {
        return initialStatusCode;
    }

    /**
     * Sets the value of the initialStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link InitialStatusCodeType }
     *     
     */
    public void setInitialStatusCode(InitialStatusCodeType value) {
        this.initialStatusCode = value;
    }

    /**
     * Gets the value of the screeningSubjectID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the screeningSubjectID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScreeningSubjectID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScreeningIdentifierType }
     * 
     * 
     */
    public List<ScreeningIdentifierType> getScreeningSubjectID() {
        if (screeningSubjectID == null) {
            screeningSubjectID = new ArrayList<ScreeningIdentifierType>();
        }
        return this.screeningSubjectID;
    }

    /**
     * Gets the value of the screeningSearchTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link ScreeningSearchTypeCode }
     *     
     */
    public ScreeningSearchTypeCode getScreeningSearchTypeCode() {
        return screeningSearchTypeCode;
    }

    /**
     * Sets the value of the screeningSearchTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScreeningSearchTypeCode }
     *     
     */
    public void setScreeningSearchTypeCode(ScreeningSearchTypeCode value) {
        this.screeningSearchTypeCode = value;
    }

    /**
     * Gets the value of the screeningSearchTypeQualifierCode property.
     * 
     * @return
     *     possible object is
     *     {@link ScreeningSearchTypeQualifierCodeType }
     *     
     */
    public ScreeningSearchTypeQualifierCodeType getScreeningSearchTypeQualifierCode() {
        return screeningSearchTypeQualifierCode;
    }

    /**
     * Sets the value of the screeningSearchTypeQualifierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScreeningSearchTypeQualifierCodeType }
     *     
     */
    public void setScreeningSearchTypeQualifierCode(ScreeningSearchTypeQualifierCodeType value) {
        this.screeningSearchTypeQualifierCode = value;
    }

    /**
     * Gets the value of the screeningUser property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the screeningUser property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScreeningUser().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScreeningUserType }
     * 
     * 
     */
    public List<ScreeningUserType> getScreeningUser() {
        if (screeningUser == null) {
            screeningUser = new ArrayList<ScreeningUserType>();
        }
        return this.screeningUser;
    }

    /**
     * Gets the value of the serviceLevelCode property.
     * 
     * @return
     *     possible object is
     *     {@link CodeType }
     *     
     */
    public CodeType getServiceLevelCode() {
        return serviceLevelCode;
    }

    /**
     * Sets the value of the serviceLevelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeType }
     *     
     */
    public void setServiceLevelCode(CodeType value) {
        this.serviceLevelCode = value;
    }

    /**
     * Gets the value of the questionSetID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getQuestionSetID() {
        return questionSetID;
    }

    /**
     * Sets the value of the questionSetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setQuestionSetID(IdentifierType value) {
        this.questionSetID = value;
    }

    /**
     * Gets the value of the searchAbuse property.
     * 
     * @return
     *     possible object is
     *     {@link SearchAbuseType }
     *     
     */
    public SearchAbuseType getSearchAbuse() {
        return searchAbuse;
    }

    /**
     * Sets the value of the searchAbuse property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchAbuseType }
     *     
     */
    public void setSearchAbuse(SearchAbuseType value) {
        this.searchAbuse = value;
    }

    /**
     * Gets the value of the searchAlcohol property.
     * 
     * @return
     *     possible object is
     *     {@link SearchAlcoholType }
     *     
     */
    public SearchAlcoholType getSearchAlcohol() {
        return searchAlcohol;
    }

    /**
     * Sets the value of the searchAlcohol property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchAlcoholType }
     *     
     */
    public void setSearchAlcohol(SearchAlcoholType value) {
        this.searchAlcohol = value;
    }

    /**
     * Gets the value of the searchCredit property.
     * 
     * @return
     *     possible object is
     *     {@link SearchCreditType }
     *     
     */
    public SearchCreditType getSearchCredit() {
        return searchCredit;
    }

    /**
     * Sets the value of the searchCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchCreditType }
     *     
     */
    public void setSearchCredit(SearchCreditType value) {
        this.searchCredit = value;
    }

    /**
     * Gets the value of the searchCriminal property.
     * 
     * @return
     *     possible object is
     *     {@link SearchCriminalType }
     *     
     */
    public SearchCriminalType getSearchCriminal() {
        return searchCriminal;
    }

    /**
     * Sets the value of the searchCriminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchCriminalType }
     *     
     */
    public void setSearchCriminal(SearchCriminalType value) {
        this.searchCriminal = value;
    }

    /**
     * Gets the value of the searchDrug property.
     * 
     * @return
     *     possible object is
     *     {@link SearchDrugType }
     *     
     */
    public SearchDrugType getSearchDrug() {
        return searchDrug;
    }

    /**
     * Sets the value of the searchDrug property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchDrugType }
     *     
     */
    public void setSearchDrug(SearchDrugType value) {
        this.searchDrug = value;
    }

    /**
     * Gets the value of the searchEducation property.
     * 
     * @return
     *     possible object is
     *     {@link SearchEducationType }
     *     
     */
    public SearchEducationType getSearchEducation() {
        return searchEducation;
    }

    /**
     * Sets the value of the searchEducation property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchEducationType }
     *     
     */
    public void setSearchEducation(SearchEducationType value) {
        this.searchEducation = value;
    }

    /**
     * Gets the value of the searchEmployment property.
     * 
     * @return
     *     possible object is
     *     {@link SearchEmploymentType }
     *     
     */
    public SearchEmploymentType getSearchEmployment() {
        return searchEmployment;
    }

    /**
     * Sets the value of the searchEmployment property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchEmploymentType }
     *     
     */
    public void setSearchEmployment(SearchEmploymentType value) {
        this.searchEmployment = value;
    }

    /**
     * Gets the value of the searchLicense property.
     * 
     * @return
     *     possible object is
     *     {@link SearchLicenseType }
     *     
     */
    public SearchLicenseType getSearchLicense() {
        return searchLicense;
    }

    /**
     * Sets the value of the searchLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchLicenseType }
     *     
     */
    public void setSearchLicense(SearchLicenseType value) {
        this.searchLicense = value;
    }

    /**
     * Gets the value of the searchMilitary property.
     * 
     * @return
     *     possible object is
     *     {@link SearchMilitaryType }
     *     
     */
    public SearchMilitaryType getSearchMilitary() {
        return searchMilitary;
    }

    /**
     * Sets the value of the searchMilitary property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchMilitaryType }
     *     
     */
    public void setSearchMilitary(SearchMilitaryType value) {
        this.searchMilitary = value;
    }

    /**
     * Gets the value of the searchOther property.
     * 
     * @return
     *     possible object is
     *     {@link SearchOtherType }
     *     
     */
    public SearchOtherType getSearchOther() {
        return searchOther;
    }

    /**
     * Sets the value of the searchOther property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchOtherType }
     *     
     */
    public void setSearchOther(SearchOtherType value) {
        this.searchOther = value;
    }

    /**
     * Gets the value of the searchReference property.
     * 
     * @return
     *     possible object is
     *     {@link SearchReferenceType }
     *     
     */
    public SearchReferenceType getSearchReference() {
        return searchReference;
    }

    /**
     * Sets the value of the searchReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchReferenceType }
     *     
     */
    public void setSearchReference(SearchReferenceType value) {
        this.searchReference = value;
    }

    /**
     * Gets the value of the searchSanction property.
     * 
     * @return
     *     possible object is
     *     {@link SearchSanctionType }
     *     
     */
    public SearchSanctionType getSearchSanction() {
        return searchSanction;
    }

    /**
     * Sets the value of the searchSanction property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchSanctionType }
     *     
     */
    public void setSearchSanction(SearchSanctionType value) {
        this.searchSanction = value;
    }

    /**
     * Gets the value of the attachment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attachment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttachment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttachmentType }
     * 
     * 
     */
    public List<AttachmentType> getAttachment() {
        if (attachment == null) {
            attachment = new ArrayList<AttachmentType>();
        }
        return this.attachment;
    }

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoteType }
     * 
     * 
     */
    public List<NoteType> getComment() {
        if (comment == null) {
            comment = new ArrayList<NoteType>();
        }
        return this.comment;
    }

    /**
     * Gets the value of the additionalItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdditionalItemType }
     * 
     * 
     */
    public List<AdditionalItemType> getAdditionalItem() {
        if (additionalItem == null) {
            additionalItem = new ArrayList<AdditionalItemType>();
        }
        return this.additionalItem;
    }

    /**
     * Gets the value of the userArea property.
     * 
     * @return
     *     possible object is
     *     {@link UserAreaType }
     *     
     */
    public UserAreaType getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAreaType }
     *     
     */
    public void setUserArea(UserAreaType value) {
        this.userArea = value;
    }

}
