//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SpendingAccountTypeCodeEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SpendingAccountTypeCodeEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="FSAHealthCare"/>
 *     &lt;enumeration value="FSADependentCare"/>
 *     &lt;enumeration value="HealthReimbursementAccount"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SpendingAccountTypeCodeEnumType")
@XmlEnum
public enum SpendingAccountTypeCodeEnumType {

    @XmlEnumValue("FSAHealthCare")
    FSA_HEALTH_CARE("FSAHealthCare"),
    @XmlEnumValue("FSADependentCare")
    FSA_DEPENDENT_CARE("FSADependentCare"),
    @XmlEnumValue("HealthReimbursementAccount")
    HEALTH_REIMBURSEMENT_ACCOUNT("HealthReimbursementAccount");
    private final String value;

    SpendingAccountTypeCodeEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SpendingAccountTypeCodeEnumType fromValue(String v) {
        for (SpendingAccountTypeCodeEnumType c: SpendingAccountTypeCodeEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
