//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.openapplications.oagis._9.AmountType;


/**
 * <p>Java class for SpendingAccountCoverageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpendingAccountCoverageType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.hr-xml.org/3}ID" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}SpendingAccountTypeCode" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}ElectedPlanID" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}GroupNumberID" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}ContractConfigurationID" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}BenefitReportingIDs" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}PlanParticipationSuspensionDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}PlanYear" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}PlanStartDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}PlanEndDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}SpendingAccountContribution" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}RolloverBalanceAmount" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}Carrier" minOccurs="0"/>
 *         &lt;element ref="{http://www.hr-xml.org/3}UserArea" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.hr-xml.org/3}EffectiveDateAttributeGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpendingAccountCoverageType", propOrder = {
    "id",
    "spendingAccountTypeCode",
    "electedPlanID",
    "groupNumberID",
    "contractConfigurationID",
    "benefitReportingIDs",
    "planParticipationSuspensionDate",
    "planYear",
    "planStartDate",
    "planEndDate",
    "spendingAccountContribution",
    "rolloverBalanceAmount",
    "carrier",
    "userArea"
})
public class SpendingAccountCoverageType {

    @XmlElement(name = "ID")
    protected IdentifierType id;
    @XmlElement(name = "SpendingAccountTypeCode")
    protected SpendingAccountTypeCodeType spendingAccountTypeCode;
    @XmlElement(name = "ElectedPlanID")
    protected IdentifierType electedPlanID;
    @XmlElement(name = "GroupNumberID")
    protected IdentifierType groupNumberID;
    @XmlElement(name = "ContractConfigurationID")
    protected List<IdentifierType> contractConfigurationID;
    @XmlElement(name = "BenefitReportingIDs")
    protected IDSetType benefitReportingIDs;
    @XmlList
    @XmlElement(name = "PlanParticipationSuspensionDate")
    protected List<String> planParticipationSuspensionDate;
    @XmlElement(name = "PlanYear")
    protected XMLGregorianCalendar planYear;
    @XmlList
    @XmlElement(name = "PlanStartDate")
    protected List<String> planStartDate;
    @XmlList
    @XmlElement(name = "PlanEndDate")
    protected List<String> planEndDate;
    @XmlElement(name = "SpendingAccountContribution")
    protected List<SpendingAccountContributionType> spendingAccountContribution;
    @XmlElement(name = "RolloverBalanceAmount")
    protected AmountType rolloverBalanceAmount;
    @XmlElement(name = "Carrier")
    protected CarrierType carrier;
    @XmlElement(name = "UserArea")
    protected UserAreaType userArea;
    @XmlAttribute(name = "validFrom")
    protected List<String> validFrom;
    @XmlAttribute(name = "validTo")
    protected List<String> validTo;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setID(IdentifierType value) {
        this.id = value;
    }

    /**
     * Gets the value of the spendingAccountTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link SpendingAccountTypeCodeType }
     *     
     */
    public SpendingAccountTypeCodeType getSpendingAccountTypeCode() {
        return spendingAccountTypeCode;
    }

    /**
     * Sets the value of the spendingAccountTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpendingAccountTypeCodeType }
     *     
     */
    public void setSpendingAccountTypeCode(SpendingAccountTypeCodeType value) {
        this.spendingAccountTypeCode = value;
    }

    /**
     * Gets the value of the electedPlanID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getElectedPlanID() {
        return electedPlanID;
    }

    /**
     * Sets the value of the electedPlanID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setElectedPlanID(IdentifierType value) {
        this.electedPlanID = value;
    }

    /**
     * Gets the value of the groupNumberID property.
     * 
     * @return
     *     possible object is
     *     {@link IdentifierType }
     *     
     */
    public IdentifierType getGroupNumberID() {
        return groupNumberID;
    }

    /**
     * Sets the value of the groupNumberID property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentifierType }
     *     
     */
    public void setGroupNumberID(IdentifierType value) {
        this.groupNumberID = value;
    }

    /**
     * Gets the value of the contractConfigurationID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contractConfigurationID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContractConfigurationID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getContractConfigurationID() {
        if (contractConfigurationID == null) {
            contractConfigurationID = new ArrayList<IdentifierType>();
        }
        return this.contractConfigurationID;
    }

    /**
     * Gets the value of the benefitReportingIDs property.
     * 
     * @return
     *     possible object is
     *     {@link IDSetType }
     *     
     */
    public IDSetType getBenefitReportingIDs() {
        return benefitReportingIDs;
    }

    /**
     * Sets the value of the benefitReportingIDs property.
     * 
     * @param value
     *     allowed object is
     *     {@link IDSetType }
     *     
     */
    public void setBenefitReportingIDs(IDSetType value) {
        this.benefitReportingIDs = value;
    }

    /**
     * Gets the value of the planParticipationSuspensionDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the planParticipationSuspensionDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlanParticipationSuspensionDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPlanParticipationSuspensionDate() {
        if (planParticipationSuspensionDate == null) {
            planParticipationSuspensionDate = new ArrayList<String>();
        }
        return this.planParticipationSuspensionDate;
    }

    /**
     * Gets the value of the planYear property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPlanYear() {
        return planYear;
    }

    /**
     * Sets the value of the planYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPlanYear(XMLGregorianCalendar value) {
        this.planYear = value;
    }

    /**
     * The PlanStartDate and PlanEndDate components are typically used to communicate a partial plan-year or plan period other than a year.Gets the value of the planStartDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the planStartDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlanStartDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPlanStartDate() {
        if (planStartDate == null) {
            planStartDate = new ArrayList<String>();
        }
        return this.planStartDate;
    }

    /**
     * The PlanStartDate and PlanEndDate components are typically used to communicate a partial plan-year or plan period other than a year.Gets the value of the planEndDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the planEndDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlanEndDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPlanEndDate() {
        if (planEndDate == null) {
            planEndDate = new ArrayList<String>();
        }
        return this.planEndDate;
    }

    /**
     * Gets the value of the spendingAccountContribution property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spendingAccountContribution property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpendingAccountContribution().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpendingAccountContributionType }
     * 
     * 
     */
    public List<SpendingAccountContributionType> getSpendingAccountContribution() {
        if (spendingAccountContribution == null) {
            spendingAccountContribution = new ArrayList<SpendingAccountContributionType>();
        }
        return this.spendingAccountContribution;
    }

    /**
     * Gets the value of the rolloverBalanceAmount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountType }
     *     
     */
    public AmountType getRolloverBalanceAmount() {
        return rolloverBalanceAmount;
    }

    /**
     * Sets the value of the rolloverBalanceAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountType }
     *     
     */
    public void setRolloverBalanceAmount(AmountType value) {
        this.rolloverBalanceAmount = value;
    }

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link CarrierType }
     *     
     */
    public CarrierType getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarrierType }
     *     
     */
    public void setCarrier(CarrierType value) {
        this.carrier = value;
    }

    /**
     * Gets the value of the userArea property.
     * 
     * @return
     *     possible object is
     *     {@link UserAreaType }
     *     
     */
    public UserAreaType getUserArea() {
        return userArea;
    }

    /**
     * Sets the value of the userArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAreaType }
     *     
     */
    public void setUserArea(UserAreaType value) {
        this.userArea = value;
    }

    /**
     * Gets the value of the validFrom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validFrom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidFrom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValidFrom() {
        if (validFrom == null) {
            validFrom = new ArrayList<String>();
        }
        return this.validFrom;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validTo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidTo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getValidTo() {
        if (validTo == null) {
            validTo = new ArrayList<String>();
        }
        return this.validTo;
    }

}
