//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.06 at 10:26:45 PM EST 
//


package org.hr_xml._3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WageHourCoverageEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WageHourCoverageEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *     &lt;enumeration value="Exempt"/>
 *     &lt;enumeration value="Non-exempt"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "WageHourCoverageEnumType")
@XmlEnum
public enum WageHourCoverageEnumType {

    @XmlEnumValue("Exempt")
    EXEMPT("Exempt"),
    @XmlEnumValue("Non-exempt")
    NON_EXEMPT("Non-exempt");
    private final String value;

    WageHourCoverageEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WageHourCoverageEnumType fromValue(String v) {
        for (WageHourCoverageEnumType c: WageHourCoverageEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
